name: dat640
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytest
  - ipykernel
  - jupyter
  - numpy
  - pandas
  - scikit-learn
  - nltk
  - sqlitedict
  - matplotlib
  - transformers
  - pip:
    - rank-bm25
